export type ProviderLocale = "zh-CN" | "en";

export const providerCopy = {
  "zh-CN": {
    title: "模型与提供商",
    subtitle: "管理模型服务、模型目录和默认模型。配置保存后会立即出现在任务输入框的模型选择器中。",
    global: "全局",
    project: "当前项目",
    globalHint: "适用于所有项目",
    projectHint: "只覆盖当前项目",
    addProvider: "添加 Provider",
    presets: "快速添加",
    custom: "自定义",
    testConnection: "测试连接",
    discoverModels: "发现模型",
    discoveredModels: "发现并同步了 {count} 个模型",
    noProviders: "还没有 Provider",
    noProvidersBody: "添加一个 OpenAI-compatible Provider，然后为它配置模型。",
    providerId: "Provider ID",
    providerName: "显示名称",
    baseUrl: "Base URL",
    endpoint: "完整 Endpoint（可选）",
    apiKey: "API Key 环境变量",
    apiKeyPlaceholder: "DEEPSEEK_API_KEY",
    package: "协议",
    save: "保存",
    cancel: "取消",
    edit: "编辑",
    remove: "删除",
    models: "个模型",
    addModel: "添加模型",
    modelId: "模型 ID",
    modelName: "显示名称",
    upstreamModelId: "上游 modelID",
    context: "上下文",
    output: "最大输出",
    default: "默认",
    setDefault: "设为默认",
    noModels: "还没有模型",
    advanced: "高级配置 JSON",
    advancedHint: "常规配置请使用上面的图形界面；只有需要批量编辑时才使用 JSON。",
    saveJson: "保存 JSON",
    inherited: "当前运行时会合并全局配置和项目覆盖。",
    deleteProviderConfirm: "删除这个 Provider 及其模型？",
    deleteModelConfirm: "删除这个模型？",
    invalidProviderId: "Provider ID 不能为空，也不能包含 /。",
    invalidModelId: "模型 ID 不能为空，也不能包含 /。",
    loading: "正在读取配置…",
    globalPath: "~/.config/lumencortex/lumencortex.json",
    projectPath: "项目根目录/lumencortex.json",
    openaiCompatible: "OpenAI Compatible",
    envHint: "这里只填写环境变量名。LumenCortex 会保存 {env:VAR_NAME} 引用，不会把真实密钥写入配置文件。",
    emptyProjectScope: "当前项目没有覆盖配置，将继承全局 Provider。",
    effectiveDefault: "当前默认"
  },
  en: {
    title: "Models & Providers",
    subtitle: "Manage model services, model catalogs, and the default model. Saved models appear immediately in the task composer.",
    global: "Global",
    project: "Project",
    globalHint: "Used by every project",
    projectHint: "Overrides this project only",
    addProvider: "Add provider",
    presets: "Quick add",
    custom: "Custom",
    testConnection: "Test connection",
    discoverModels: "Discover models",
    discoveredModels: "Discovered and synced {count} models",
    noProviders: "No providers yet",
    noProvidersBody: "Add an OpenAI-compatible provider, then define one or more models.",
    providerId: "Provider ID",
    providerName: "Display name",
    baseUrl: "Base URL",
    endpoint: "Exact endpoint (optional)",
    apiKey: "API key environment variable",
    apiKeyPlaceholder: "DEEPSEEK_API_KEY",
    package: "Protocol",
    save: "Save",
    cancel: "Cancel",
    edit: "Edit",
    remove: "Delete",
    models: "models",
    addModel: "Add model",
    modelId: "Model ID",
    modelName: "Display name",
    upstreamModelId: "Upstream modelID",
    context: "Context",
    output: "Max output",
    default: "Default",
    setDefault: "Set default",
    noModels: "No models yet",
    advanced: "Advanced JSON",
    advancedHint: "Use the graphical controls above for normal editing. JSON is intended for bulk or advanced edits.",
    saveJson: "Save JSON",
    inherited: "Runtime uses the merged result of global settings and project overrides.",
    deleteProviderConfirm: "Delete this provider and all of its models?",
    deleteModelConfirm: "Delete this model?",
    invalidProviderId: "Provider ID is required and cannot contain /.",
    invalidModelId: "Model ID is required and cannot contain /.",
    loading: "Loading provider settings…",
    globalPath: "~/.config/lumencortex/lumencortex.json",
    projectPath: "project/lumencortex.json",
    openaiCompatible: "OpenAI Compatible",
    envHint: "Enter only the environment variable name. LumenCortex stores a {env:VAR_NAME} reference and never persists the resolved secret.",
    emptyProjectScope: "This project has no overrides and inherits global providers.",
    effectiveDefault: "Effective default"
  }
} as const;
